version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    container_name: node-ts-rest-api
    restart: always
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/node-ts-rest-api
      - PORT=3000
    depends_on:
      - mongo
    command: sh -c 'npm run build && npm start'
volumes:
  mongo-data: 